### ISSUE TITLE
{{ recaptcha }}  in template 

### ISSUE THREAD

**Issue by alisharify7** [mardix/flask-recaptcha#25]
File "\venv\Lib\site-packages\flask_recaptcha.py", line 59, in get_code
return dict(recaptcha=Markup(self.get_code()))
                      ^^^^^^
NameError: name 'Markup' is not defined

**Comment by bkiziuk** [comment]
[Flask app NameError: name 'Markup' is not defined](https://stackoverflow.com/a/74753137)

but obviously this is not an ultimate solution.
